export type Auto = {
  make: string
  model: string
  barrels08: number
  barrelsa08: number
  charge120: number
  charge240: number
  city08: number
  city08u: number
  citya08: number
  citya08u: number
  citycd: number
  citye: number
  cityuf: number
  co2: number
  co2a: number
  co2tailpipeagpm: number
  co2tailpipegpm: number
  comb08: number
  comb08u: number
  comba08: number
  comba08u: number
  combe: number
  combinedcd: number
  combineduf: number
  cylinders: number
  displ: number
  drive: string
  engid: string
  eng_dscr?: string[]
  fescore: any
  fuelcost08: number
  fuelcosta08: number
  fueltype: string
  fueltype1: string
  ghgscore: any
  ghgscorea: any
  highway08: number
  highway08u: number
  highwaya08: number
  highwaya08u: number
  highwaycd: number
  highwaye: number
  highwayuf: number
  hlv: number
  hpv: number
  id: string
  lv2: number
  lv4: number
  mpgdata: string
  phevblended: string
  pv2: number
  pv4: number
  range: number
  rangecity: number
  rangecitya: number
  rangehwy: number
  rangehwya: number
  trany: string
  ucity: number
  ucitya: number
  uhighway: number
  uhighwaya: number
  vclass: string
  year: string
  yousavespend: number
  guzzler?: string
  trans_dscr?: string
  tcharger?: string
  scharger?: string
  atvtype?: string
  fueltype2: any
  rangea: any
  evmotor: any
  mfrcode: any
  c240dscr: any
  charge240b: number
  c240bdscr: any
  createdon: string
  modifiedon: string
  startstop: any
  phevcity: number
  phevhwy: number
  phevcomb: number
  basemodel: string
}
